gallery:
  title: "My Private Gallery"
  root_dir: "/var/www/dzieci/"
  host: "0.0.0.0"
  port: 8081
  sort_by: "name"
  sort_order: "asc"
  allowed_extensions:
    images: ["jpg", "jpeg", "png", "webp", "heic", "heif"]
    videos: ["mp4", "mov", "mkv"]
