gallery:
  title: "My Private Gallery"
  root_dir: "/var/www/my_photos/"
  host: "127.0.0.1"
  port: 8081
  password: ""
  allowed_extensions:
    images: ["jpg", "jpeg", "png", "webp", "heic", "heif"]
    videos: ["mp4", "mov", "mkv"]
