gallery:
  title: "My Private Gallery"
  root_dir: "/var/www/dzieci/"
  host: "0.0.0.0"
  port: 8081
  allowed_extensions:
    images: ["jpg", "jpeg", "png", "webp"]
    videos: ["mp4", "mov", "mkv"]
